# Generated by Django 5.0.6 on 2024-07-17 08:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildKombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('belister', 'belister'), ('zakuska', 'zakuska'), ('napitok', 'napitok'), ('pitsa', 'pitsa'), ('disert', 'disert')], max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'verbose_name': 'kombo child',
                'verbose_name_plural': 'kombo child',
                'db_table': 'ChildKombo',
            },
        ),
        migrations.CreateModel(
            name='ChildKomboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pizza', models.BooleanField(default=False)),
                ('overprice', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('size', models.CharField(blank=True, choices=[('KICHKINA', 'KICHKINA'), ("O'RTACHA", "O'RTACHA"), ('KATTA', 'KATTA')], max_length=10, null=True)),
                ('childkombo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kombo.childkombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'kombo child item',
                'verbose_name_plural': 'kombo child items',
                'db_table': 'ChildKomboItem',
            },
        ),
        migrations.AddField(
            model_name='childkombo',
            name='product',
            field=models.ManyToManyField(through='kombo.ChildKomboItem', to='product.product'),
        ),
        migrations.CreateModel(
            name='Kombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(999), django.core.validators.MaxValueValidator(999999)])),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('discount_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(999), django.core.validators.MaxValueValidator(999999)])),
                ('image', models.ImageField(upload_to='kombo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])])),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'kombo',
                'verbose_name_plural': 'kombo',
                'db_table': 'Kombo',
            },
        ),
        migrations.AddField(
            model_name='childkombo',
            name='kombo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kombochild', to='kombo.kombo'),
        ),
    ]
