# Generated by Django 5.0.6 on 2024-07-18 02:28

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number_userconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[user.validators.check_phone_validator]),
        ),
    ]
