# Generated by Django 5.0.6 on 2024-07-21 05:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_address_address_uniqe'),
        ('kombo', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('KOMBO', 'KOMBO')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.IntegerField()),
                ('ingredient_kombo', models.ManyToManyField(blank=True, help_text='faqat kombo uchun kiriting', related_name='just', to='product.product')),
                ('ingredient_product', models.ManyToManyField(blank=True, help_text='faqat product uchun kiriting', to='product.ingredient')),
                ('kombo', models.ForeignKey(blank=True, help_text='faqat kombo uchun kiriting', null=True, on_delete=django.db.models.deletion.CASCADE, to='kombo.kombo')),
                ('product', models.ForeignKey(blank=True, help_text='faqat product uchun kiriting', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CartItem',
                'verbose_name_plural': 'CartItems',
                'db_table': 'cartitem',
            },
        ),
        migrations.CreateModel(
            name='ItemThrough',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_pizza', models.BooleanField(default=False)),
                ('pizza_shape', models.CharField(blank=True, choices=[('KICHKINA', 'KICHKINA'), ("O'RTACHA", "O'RTACHA"), ('KATTA', 'KATTA')], help_text='Bu fieldga faqat pitsa statusi uchun kiritasiz', max_length=20, null=True, verbose_name="Pitsa o'lchami")),
                ('pizza_volume', models.CharField(blank=True, choices=[('YUPQA', 'YUPQA'), ('QALIN', 'QALIN')], help_text='Bu fieldga faqat pitsa statusi uchun kiritasiz', max_length=20, null=True, verbose_name="Pitsa ko'rinishi")),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cartitem')),
            ],
            options={
                'verbose_name': 'ItemThrough',
                'verbose_name_plural': 'ItemThrough',
                'db_table': 'itemthrough',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('FINISHED', 'FINISHED')], default='CREATED', max_length=20)),
                ('total_price', models.PositiveIntegerField()),
                ('order_number', models.PositiveSmallIntegerField()),
                ('time_of_order', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address')),
                ('items', models.ManyToManyField(blank=True, through='order.ItemThrough', to='order.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='itemthrough',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
