# Generated by Django 5.0.6 on 2024-07-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cartitem_ingredient_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemthrough',
            name='cartitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemthrough', to='order.cartitem'),
        ),
    ]
