# Generated by Django 5.0.6 on 2024-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_address_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
